# Generated by Django 5.0.6 on 2024-06-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=100)),
                ('is_archived', models.BooleanField(default=False)),
                ('parent_document', models.CharField(max_length=255)),
                ('content', models.JSONField()),
                ('cover_image', models.TextField()),
                ('icon', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
