# Generated by Django 4.1.13 on 2024-06-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlockNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("user_id", models.CharField(max_length=75)),
                ("is_archived", models.BooleanField(default=False)),
                ("parent_document", models.CharField(max_length=75)),
                ("content", models.JSONField()),
                ("cover_image", models.CharField(max_length=5000)),
                ("icon", models.CharField(max_length=5000)),
                ("is_published", models.BooleanField(default=False)),
            ],
        ),
    ]
