# Generated by Django 4.1.13 on 2024-06-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pseudo_kb", "0002_blocknote_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blocknote",
            name="cover_image",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="blocknote",
            name="icon",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="blocknote",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="blocknote",
            name="user_id",
            field=models.CharField(max_length=100),
        ),
    ]
